### ISSUE TITLE
Need API key

### ISSUE THREAD

**Issue by cosad3s** [sc4rfurry/SubHuntr99#2]
Unfortunatelly, it seems that subdomainfinder.c99.nl needs API key to be purchased here now : https://api.c99.nl/dashboard/shop :(
And the domain to use is now: https://api.c99.nl/subdomainfinder?key=<key>&domain=example.com.

**Comment by sc4rfurry** [comment]
fixed the above issue in the following [commit](https://github.com/sc4rfurry/SubHuntr99/commit/06e7dca9dbf2af2d333d633683ed4ccf59ae2079)

@cosad3s Thanks for raising the following issue.
